Product_CatalogAndWarehouse_Inventory/Models/UserManagement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CompareAttribute = System.ComponentModel.DataAnnotations.CompareAttribute;

namespace Product_CatalogAndWarehouse_Inventory.Models
{
    public class UserModel
    {
        public int SerialNo { get; set; }        
        public int registration_id { get; set; }
        // Validation for Name (1.required 2.Length - max(50), min(3) 3. Only characters)
        [Required]
        [StringLength(50, ErrorMessage = "Maximum 50 Characters Required"), MinLength(3, ErrorMessage = "Minimum of 3 characters required")]
        [RegularExpression("^[A-z]+[a-z]$", ErrorMessage = "Only Chracters are allowed")]
        // Return the value or assign the value to Name
        public string Name { get; set; }
        // Validation for Email (1.required, 2.Email Format 
        [Required]
        [RegularExpression("^[A-Za-z0-9]+@[a-z]+\\.[a-z]{2,3}$", ErrorMessage = "Invalid Email")]
        // Return the value or assign the value to Email
        public string Email { get; set; }
        // Validation for Mobile Number (1.required, 2. Allowed only numbers and length must be 10)
        [Required]
        [RegularExpression("^[0-9]{10}$", ErrorMessage = "Only numbers are allowed and Range must be 10")]
        [Display(Name = "Mobile Number")]
        // Return the value or assign the value to Mobile Number
        public string MobileNumber { get; set; }
        // Validation for Gender (1.required)
        [Required]
        // Return the value or assign the value to Gender
        public string Gender { get; set; }
        // Validation for city_Id (1.required)
        [Required]
        // Return the CityID or assign the ID of City
        public int city_Id { get; set; }
        // Return the name or assign the name of City       
        public string City { get; set; }
        // Validation for Password (1.required, 2.Password Format, 3.password dot format validation
        [Required(ErrorMessage = "Please enter Password")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@#!%*?&])[A-Za-z\d$@#!%*?&]{8,}$",
            ErrorMessage = "Must contain at least one number,uppercase,lowercase letter,special character and 8 or more characters")]
        [DataType(DataType.Password)]
        // Return the password
        public string Password { get; set; }
        // Validation for Password (1.required, 2.Compare password validation
        [Required(ErrorMessage = "Please enter Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password")]
        // Return the Confirm_Password
        public string Confirm_Password { get; set; }       
        public List<SelectListItem> Cities { get; set; } = new List<SelectListItem>();
        public List<UserModel> userList { get; set; }
        public List<UserModel> EditList { get; set; }
        public double? Page_Count { get; set; }

    }
}

Product_CatalogAndWarehouse_Inventory/Controllers/UserManagementController.cs
using Product_CatalogAndWarehouse_Inventory.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace Product_CatalogAndWarehouse_Inventory.Controllers
{
    public class UserManagementController : Controller
    {
        StringBuilder sb;
        Dal obj_dal;
        DataTable dt;

        public List<UserModel> UserDataList()
        {
            List<UserModel> userdataList = new List<UserModel>();
            // Used to check row count grater than 0
            if (dt.Rows.Count > 0)
            {
                // code to be executed repeatedly until row count less than 0
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    var user = new UserModel();
                    // Add serial number using row count in list 
                    user.SerialNo = i + 1;
                    user.registration_id = Convert.ToInt32(dt.Rows[i]["Registration_ID"].ToString());
                    // Get the value of Name
                    user.Name = dt.Rows[i]["Name"].ToString();
                    // Get the value of Email ID
                    user.Email = dt.Rows[i]["Email"].ToString();
                    // Get the value of Mobile Number
                    user.MobileNumber = dt.Rows[i]["Mobile_Number"].ToString();
                    // Get the value of Gender
                    user.Gender = dt.Rows[i]["Gender"].ToString();
                    // Get the value of City_Name
                    user.City = dt.Rows[i]["City_Name"].ToString();
                    // Add user data into userdataList
                    userdataList.Add(user);
                }
            }
            return userdataList;
        }

        public ActionResult Registration()
        {
            UserModel model = new UserModel();
            // Variable declaration if Tempdata is not null then pass the stored value in view
            var tempdata = TempData["Model"];
            if (tempdata != null)
            {
                return View(tempdata);
            }
            // Function call
            model.Cities = Getcitydatalist();
            // Onclick button text change
            TempData["Message"] = "Submit";
            return View(model);
        }

        public List<SelectListItem> Getcitydatalist()
        {
            // Dal Function call from Dal class
            obj_dal = new Dal();
            dt = new DataTable();
            // Applied SELECT Query to get data of city table from database
            sb = new StringBuilder();
            //sb.Append("SELECT * FROM tbl_City");
            sb.Append("SELECT City_ID, City_Name FROM tbl_City");
            // GET_DATATABLE function call from Dal class to fill the table data
            dt = obj_dal.GET_DATATABLE(sb.ToString());
            List<SelectListItem> cityList = new List<SelectListItem>();
            SelectListItem city;
            // Used to check row count grater than 0
            if (dt.Rows.Count > 0)
            {
                // code to be executed repeatedly until row count less than 0
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    city = new SelectListItem();
                    // get the value of City_ID
                    city.Value = dt.Rows[i]["City_ID"].ToString();
                    // Get the value of City_Name
                    city.Text = dt.Rows[i]["City_Name"].ToString();
                    // Add City_ID and City_Name into city
                    cityList.Add(city);
                }
            }
            return cityList;
        }

        [HttpPost]
        public ActionResult Registration(UserModel userModel, int? ID)
        {
            obj_dal = new Dal();
            sb = new StringBuilder();
            // If statement condition used for Update data and else statement used for Insert data
            if (ID != null)
            {
                // Used to Applied SELECT Query to count Email data from database using model
                sb.Append("SELECT COUNT(Email) FROM tbl_Registration WHERE Email = '" + userModel.Email + "' and Registration_ID != '" + ID + "'");
                /* Variable declaration and convert into int
                   Get_SingleValue function call from Dal class to return single value*/
                int Count = Convert.ToInt32(obj_dal.Get_SingleValue(sb.ToString()));
                // If Row count value is grater then 0 so Email id must be duplicate
                if (Count > 0)
                {
                    // Error message in red color
                    ViewBag.color = "red";
                    ViewBag.Message = "Email ID Already exist";
                }
                else
                {
                    // Applied UPDATE Query to update row data in database using model
                    sb.Append("UPDATE tbl_Registration SET Name = '" + userModel.Name + "',Email = '" + userModel.Email + "',");
                    sb.Append("Mobile_Number = '" + userModel.MobileNumber + "',Gender = '" + userModel.Gender + "',City_ID = '" + userModel.city_Id + "', ");
                    sb.Append("Password = '" + userModel.Password + "' FROM tbl_Registration  Where Registration_ID ='" + ID + "'");
                    // EXECUTE_DM function call from Dal class to execute sql query
                    obj_dal.EXECUTE_DML(sb.ToString());
                    TempData["message"] = "Data updated successfully!";
                    return RedirectToAction("UserList");
                }
                userModel = new UserModel();
                // Function call
                userModel.Cities = Getcitydatalist();
            }
            else
            {
                // Used to Applied SELECT Query to count Email data from database using model
                sb.Append("SELECT COUNT(Email) FROM tbl_Registration WHERE Email = '" + userModel.Email + "'");
                /* Variable declaration and convert into int
                   Get_SingleValue function call from Dal class to return single value*/
                int Count = Convert.ToInt32(obj_dal.Get_SingleValue(sb.ToString()));
                // If Row count value is grater then 0 so Email id must be duplicate
                if (Count > 0)
                {
                    // Error message in red color
                    ViewBag.color = "red";
                    ViewBag.Message = "Email ID Already exist";
                }
                else
                {
                    sb.Append("INSERT INTO tbl_Registration (Name, Email, Mobile_Number, Gender, City_ID, Password)");
                    sb.Append("VALUES ('" + userModel.Name + "','" + userModel.Email + "','" + userModel.MobileNumber + "',");
                    sb.Append("'" + userModel.Gender + "','" + userModel.city_Id + "','" + userModel.Password + "')");
                    // EXECUTE_DM function call from Dal class to execute sql query
                    obj_dal.EXECUTE_DML(sb.ToString());
                    // Success Message in green color
                    TempData["message"] = "Data saved successfully!";
                    // Clear the model
                    ModelState.Clear();
                    return RedirectToAction("UserList");
                }
                userModel = new UserModel();
                // Function call
                userModel.Cities = Getcitydatalist();
            }
            return View(userModel);
        }

        public ActionResult UserList(UserModel userModel)
        {
            // Stored seesion value in variable
            var session = Session["Username"];
            /* if statement is used check seesion value is null and 
             * if it's null then redirect login page */
            if (session == null)
            {
                return RedirectToAction("Login");
            }
            // Dal Function call from Dal class
            obj_dal = new Dal();
            sb = new StringBuilder();
            /* Variable declaration of tempdata
             * if tempdata is not null then retrive userList to view */
            var tempdata = TempData["Model"];
            if (tempdata != null)
            {
                return View(tempdata);
            }
            /* Applied SELECT Query to get data of user from registration table in database */
            sb.Clear();
            sb.Append("SELECT r.Registration_ID,r.Name,r.Email,r.Mobile_Number,r.Gender,c.City_Name ");
            sb.Append("FROM tbl_Registration r ");
            sb.Append("INNER JOIN tbl_City c ON r.City_ID = c.City_ID ");
            // GET_DATATABLE function call from Dal class to fill the table data
            dt = obj_dal.GET_DATATABLE(sb.ToString());
            // Function Call           
            userModel.userList = UserDataList();
            return View(userModel);
        }

        public ActionResult DeleteUserData(int registraion_id)
        {
            // Dal Function call from Dal class
            obj_dal = new Dal();
            // Applied DELETE Query to delete row record in list and table 
            sb = new StringBuilder();
            sb.Append("DELETE FROM tbl_Registration where Registration_ID= '" + registraion_id + "'");
            // EXECUTE_DM function call from Dal class to execute sql query
            obj_dal.EXECUTE_DML(sb.ToString());
            return RedirectToAction("UserList");
        }

        public ActionResult EditUserData(int registration_id)
        {
            // Dal Function call from Dal class
            obj_dal = new Dal();
            UserModel userModel = new UserModel();
            // Applied SELECT Query to select row record in list and table for particular Reg_ID
            sb = new StringBuilder();

Product_CatalogAndWarehouse_Inventory/Views/UserManagement/About.cshtml
<link href="~/Admin_Template/css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="~/Admin_Template/css/plugins/steps/jquery.steps.css" rel="stylesheet">







<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-5">
            <div class="jumbotron">
                <h1>Steps</h1>
                <p>Smart UI component which allows you to easily create wizard-like interfaces.</p>
                <p>
                    <a href="http://www.jquery-steps.com/GettingStarted" target="_blank" class="btn btn-primary btn-lg" role="button">Learn more about jQuery Steps</a>
                </p>
            </div>
        </div>
        <div class="col-lg-7">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Basic Wizzard</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <p>
                        This is basic example of Step
                    </p>
                    <div id="wizard">
                        <h1>First Step</h1>
                        <div class="step-content">
                            <div class="text-center m-t-md">
                                <h2>Hello in Step 1</h2>
                                <p>
                                    This is the first content.
                                </p>
                            </div>
                        </div>

                        <h1>Second Step</h1>
                        <div class="step-content">
                            <div class="text-center m-t-md">
                                <h2>This is step 2</h2>
                                <p>
                                    This content is diferent than the first one.
                                </p>
                            </div>
                        </div>

                        <h1>Third Step</h1>
                        <div class="step-content">
                            <div class="text-center m-t-md">
                                <h2>This is step 3</h2>
                                <p>
                                    This is last content.
                                </p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Wizard with Validation</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#">Config option 1</a>
                            </li>
                            <li>
                                <a href="#">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <h2>
                        Validation Wizard Form
                    </h2>
                    <p>
                        This example show how to use Steps with jQuery Validation plugin.
                    </p>

                    <form id="form" action="#" class="wizard-big">
                        <h1>Account</h1>
                        <fieldset>
                            <h2>Account Information</h2>
                            <div class="row">
                                <div class="col-lg-8">
                                    <div class="form-group">
                                        <label>Username *</label>
                                        <input id="userName" name="userName" type="text" class="form-control required">
                                    </div>
                                    <div class="form-group">
                                        <label>Password *</label>
                                        <input id="password" name="password" type="text" class="form-control required">
                                    </div>
                                    <div class="form-group">
                                        <label>Confirm Password *</label>
                                        <input id="confirm" name="confirm" type="text" class="form-control required">
                                    </div>
                                </div>
                                <div class="col-lg-4">
                                    <div class="text-center">
                                        <div style="margin-top: 20px">
                                            <i class="fa fa-sign-in" style="font-size: 180px;color: #e5e5e5 "></i>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </fieldset>
                        <h1>Profile</h1>
                        <fieldset>
                            <h2>Profile Information</h2>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>First name *</label>
                                        <input id="name" name="name" type="text" class="form-control required">
                                    </div>
                                    <div class="form-group">
                                        <label>Last name *</label>
                                        <input id="surname" name="surname" type="text" class="form-control required">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Email *</label>
                                        <input id="email" name="email" type="text" class="form-control required email">
                                    </div>
                                    <div class="form-group">
                                        <label>Address *</label>
                                        <input id="address" name="address" type="text" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <h1>Warning</h1>
                        <fieldset>
                            <div class="text-center" style="margin-top: 120px">
                                <h2>You did it Man :-)</h2>
                            </div>
                        </fieldset>

                        <h1>Finish</h1>
                        <fieldset>
                            <h2>Terms and Conditions</h2>
                            <input id="acceptTerms" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms">I agree with the Terms and Conditions.</label>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="footer">
    <div class="pull-right">
        10GB of <strong>250GB</strong> Free.
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2017
    </div>
</div>







@section  Scripts {
    <!-- Steps -->
    <script src="~/Admin_Template/js/plugins/staps/jquery.steps.min.js"></script>

    <!-- Jquery Validate -->
    <script src="~/Admin_Template/js/plugins/validate/jquery.validate.min.js"></script>

    <script>
        $(document).ready(function () {
            $("#wizard").steps();
            $("#form").steps({
                bodyTag: "fieldset",
                onStepChanging: function (event, currentIndex, newIndex) {
                

                    // Start validation; Prevent going forward if false
                    return form.valid();
                },
                onStepChanged: function (event, currentIndex, priorIndex) {
                    // Suppress (skip) "Warning" step if the user is old enough.
                    if (currentIndex === 2 && Number($("#age").val()) >= 18) {
                        $(this).steps("next");
                    }

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                    if (currentIndex === 2 && priorIndex === 3) {
                        $(this).steps("previous");
                    }
                },
                onFinishing: function (event, currentIndex) {
                    var form = $(this);

                    // Disable validation on fields that are disabled.
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                    form.validate().settings.ignore = ":disabled";

                    // Start validation; Prevent form submission if false
                    return form.valid();
                },
                onFinished: function (event, currentIndex) {
                    var form = $(this);

                    // Submit form input
                    form.submit();
                }
            }).validate({
                errorPlacement: function (error, element) {
                    element.before(error);
                },
                rules: {
                    confirm: {
                        equalTo: "#password"
                    }
                }
            });
        });</script>
}

Product_CatalogAndWarehouse_Inventory/Views/UserManagement/Login.cshtml
@model Product_CatalogAndWarehouse_Inventory.Models.UserModel
@{
    ViewBag.Title = "Login";
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>@ViewBag.Title| Product Catalog and Warehouse Inventory</title>

    <!--Used to render a bundle of CSS files-->
    @Styles.Render("~/Content/css")

    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>*@

</head>


<body class="gray-bg">

    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div>

                <h1 class="logo-name">WI+</h1>

            </div>
            <p>Login</p>
            <form class="m-t" role="form" method="post">
                <div class="form-group" style="text-align: left">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @style = "color:red" })
                </div>
                <div class="form-group" style="text-align: left">
                    @Html.TextBoxFor(m => m.Password, new { @class = "form-control", placeholder = "Password", Type = "Password" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @style = "color:red" })
                </div>
                <button type="submit" class="btn btn-primary block full-width m-b">Login</button>
                <div class="form-group" style="text-align: left">
                    @if (ViewBag.Message != null)
                    {
                        <span style="color:@Convert.ToString(ViewBag.color)">@ViewBag.Message</span>
                    }
                </div>


                @*<a href="#"><small>Forgot password?</small></a>*@
                <p class="text-muted text-center"><small>Do not have an account?</small></p>
                <a class="btn btn-sm btn-white btn-block" href="https://localhost:44390/UserManagement">Create an account</a>
            </form>
            @*<p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small> </p>*@
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

</body>
</html>

Product_CatalogAndWarehouse_Inventory/Views/UserManagement/UserList.cshtml
@model Product_CatalogAndWarehouse_Inventory.Models.UserModel

@{
    ViewBag.Title = "Userlist";
}


@if (TempData["message"] != null)
{
    <span style="color:green;"> @TempData["message"]</span>
}

<div class="ibox-content">
    <div class="table-responsive">
        <!--Table Section starts-->
        <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
                <tr>
                    <th style="width:70px">Serial No.</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Mobile Number</th>
                    <th>Gender</th>
                    <th>City Name</th>
                    <th style="width:100px">Action</th>
                </tr>
            </thead>
            <tbody>
                <!--UserList call from model-->
                @foreach (var item in Model.userList)
                {
                    <tr>
                        <td>
                            @item.SerialNo
                        </td>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Email
                        </td>
                        <td>
                            @item.MobileNumber
                        </td>
                        <td>
                            @item.Gender
                        </td>
                        <td>
                            @item.City
                        </td>
                        <td style="100px">
                            <!--Button click event for Edit data-->
                            <button class="btn btn-success btn-xs" style="margin-top:1px; margin-bottom:1px; width:58px"
                                    onclick="location.href='@Url.Action("EditUserData", "UserManagement", new { registration_id = item.registration_id })'">
                                Edit
                            </button>

                            <!--Button click event for Delete data-->
                            <a href='@Url.Action("DeleteUserData", "UserManagement", new { registraion_id = item.registration_id })'
                               class="btn btn-danger btn-xs" style="margin-bottom:1px; margin-bottom:1px; width:58px" ,
                               onclick="return confirm('Are you sure you want to delete this record?');">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <!--Table section ends-->
    </div>
</div>


<!--Scripts for Pagination and Searching-->
@section scripts{
    <script>
        $(document).ready(function () {
            $('.dataTables-example').DataTable({
                lengthMenu: [5, 10, 25, 50],
                pageLength: 5,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [

                    {

                        extend: 'csv', title: 'UserList',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        },
                        customize: function (win) {
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                .addClass('compact')
                                .css('font-size', 'inherit');
                        }
                    }
                ]
            });
        });
    </script>
}