Product_CatalogAndWarehouse_Inventory/Controllers/ProductCatalogueController.cs
using Microsoft.Ajax.Utilities;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Information;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Math;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
using Product_CatalogAndWarehouse_Inventory.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing.Printing;
using System.IO;
using System.Text;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.WebPages;
using System.Windows.Forms;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;

namespace Product_CatalogAndWarehouse_Inventory.Controllers
{
    public class ProductCatalogueController : Controller
    {
        Dal obj_dal;
        StringBuilder sb;
        DataTable dt_ProductList = new DataTable();

        public List<ProductCatalogueModel> ProductCatalogueList()
        {
            List<ProductCatalogueModel> ProductGridCatelogue = new List<ProductCatalogueModel>();
            // Use to check row count is grater than zero
            if (dt_ProductList.Rows.Count > 0)
            {
                // code to be executed repeatedly until row count less than 0 
                for (int i = 0; i < dt_ProductList.Rows.Count; i++)
                {
                    // Get the value of ProductName, TotalCost and FileImage
                    ProductCatalogueModel catalogueModel = new ProductCatalogueModel();
                    catalogueModel.ProductName = dt_ProductList.Rows[i]["ProductName"].ToString();
                    catalogueModel.WarehouseSKU = dt_ProductList.Rows[i]["WarehouseSKU"].ToString();
                    catalogueModel.TotalCost = Convert.ToDecimal(dt_ProductList.Rows[i]["TotalCost"].ToString());
                    catalogueModel.FileImage = dt_ProductList.Rows[i]["ProductImage"].ToString();
                    // Add all field value in ProductGridCatelogue list
                    ProductGridCatelogue.Add(catalogueModel);
                }
            }
            return ProductGridCatelogue;
        }

        public ActionResult AllProductList(ProductCatalogueModel catalogueModel)
        {
            // Use to check row count is grater than zero
            if (dt_ProductList.Rows.Count > 0)
            {
                // code to be executed repeatedly until row count less than 0 
                for (int i = 0; i < dt_ProductList.Rows.Count; i++)
                {
                    //Get the value of all Catalogue Product page fields
                    catalogueModel.ProductName = dt_ProductList.Rows[i]["ProductName"].ToString();
                    catalogueModel.WarehouseSKU = dt_ProductList.Rows[i]["WarehouseSKU"].ToString();
                    catalogueModel.Description = dt_ProductList.Rows[i]["Description"].ToString();
                    catalogueModel.HSCode = dt_ProductList.Rows[i]["HSCode"].ToString();
                    catalogueModel.Width = Convert.ToDecimal(dt_ProductList.Rows[i]["Width"].ToString());
                    catalogueModel.Length = Convert.ToDecimal(dt_ProductList.Rows[i]["Length"].ToString());
                    catalogueModel.Height = Convert.ToDecimal(dt_ProductList.Rows[i]["Height"].ToString());
                    catalogueModel.MaterialComposition = dt_ProductList.Rows[i]["MaterialComposition"].ToString();
                    catalogueModel.VarsanyBag = dt_ProductList.Rows[i]["VarsanyBag"].ToString();
                    catalogueModel.Colour = dt_ProductList.Rows[i]["Colour"].ToString();
                    catalogueModel.ProductWeight = Convert.ToDecimal(dt_ProductList.Rows[i]["ProductWeight"].ToString());
                    catalogueModel.BoxSize = Convert.ToDecimal(dt_ProductList.Rows[i]["BoxSize"].ToString());
                    catalogueModel.Manufaturer = dt_ProductList.Rows[i]["Manufature"].ToString();
                    catalogueModel.MailingBag = dt_ProductList.Rows[i]["MailingBag"].ToString();
                    catalogueModel.Size = dt_ProductList.Rows[i]["Size"].ToString();
                    catalogueModel.ProductCost = Convert.ToDecimal(dt_ProductList.Rows[i]["ProductCost"].ToString());
                    catalogueModel.Commision = Convert.ToDecimal(dt_ProductList.Rows[i]["Commision"].ToString());
                    catalogueModel.ShippingCost = Convert.ToDecimal(dt_ProductList.Rows[i]["ShippingCost"].ToString());
                    catalogueModel.Duty = Convert.ToDecimal(dt_ProductList.Rows[i]["Duty"].ToString());
                    catalogueModel.TotalCost = Convert.ToDecimal(dt_ProductList.Rows[i]["TotalCost"].ToString());
                    ViewBag.ImageUrl = catalogueModel.FileImage = dt_ProductList.Rows[i]["ProductImage"].ToString();
                    ViewBag.Warehouse = catalogueModel.WarehouseSKU;
                }
            }
            return View(catalogueModel);
        }

        // GET: Edit Product Catalogue
        public ActionResult AddCatalogueProduct(string sku, string ImagePath)
        {
            ProductCatalogueModel productmodel = new ProductCatalogueModel();
            /* If statement is used to check sku is null or not 
               if it is not null than fill AddCatalogueProduct page fields with corresponding WarehouseSKU*/
            if (sku != null)
            {
                obj_dal = new Dal();
                sb = new StringBuilder();
                // Applied SELECT Query to get data of tbl_ProductCatalogue from database with the use of warehousesku
                sb.Append("SELECT ProductName, WarehouseSKU, Description, HSCode, Width, Length, Height, MaterialComposition,");
                sb.Append("VarsanyBag, Colour, ProductWeight, BoxSize, BoxQuantity, Manufature, MailingBag, Size,");
                sb.Append("ProductCost, Commision, ShippingCost, Duty, TotalCost, ProductImage ");
                sb.Append("FROM tbl_ProductCatalogue  WHERE WarehouseSKU = '" + sku + "'");
                dt_ProductList = obj_dal.GET_DATATABLE(sb.ToString());
                // Function Call
                AllProductList(productmodel);          
                ViewBag.ProductName = productmodel.ProductName;
                TempData["Message"] = "Update Product";
                return View(productmodel);
            }
            ViewBag.Title = "Add Catalogue Product";
            TempData["Message"] = "Save Product";
            return View();

        }

        // POST : ADD / Edit Product Catalogue 
        [HttpPost]
        public ActionResult AddCatalogueProduct(ProductCatalogueModel product, string sku, string ImagePath)
        {
            try
            {
                string uniqueImagename = string.Empty;
                obj_dal = new Dal();
                sb = new StringBuilder();
                product.Width = product.Width ?? 0;
                product.Length = product.Length ?? 0;
                product.Height = product.Height ?? 0;
                product.ProductWeight = product.ProductWeight ?? 0;
                product.BoxSize = product.BoxSize ?? 0;
                product.BoxQuantity = product.BoxQuantity ?? 0;
                product.Commision = product.Commision ?? 0;
                product.ShippingCost = product.ShippingCost ?? 0;
                product.Duty = product.Duty ?? 0;

                /* If statement is used to check ImageFile is null or not 
                 * if it is not null than save image in UploadedIMage folder.*/
                if (product.ImageFile != null)
                {
                    // For File extension
                    string extention = Path.GetExtension(product.ImageFile.FileName.ToLower());
                    /* if extensions are not .jpg and .png then return view */
                    if (extention != ".jpg" & extention != ".png")
                    {
                        return View();
                    }
                    // Set directory path
                    string path = Server.MapPath("~/UploadedImage/");
                    //if directory is alredy exists then remove it with all file and create new directory
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    //Generate new unique image name
                    uniqueImagename = Guid.NewGuid().ToString() + System.IO.Path.GetExtension(product.ImageFile.FileName);
                    //For file path
                    string filePath = Path.Combine(path, uniqueImagename);
                    //Save as file in given file path
                    product.ImageFile.SaveAs(filePath);
                }
                /* If statement is used to check sku is null or not 
                 * if it is not null than Update Add catelogue product page field
                 * otherwise insert Add catelogue product page field data into database.*/
                if (sku != null)
                {
                    // Applied Select query for duplicate value of WarehouseSKU
                    sb.Append("SELECT COUNT(WarehouseSKU) FROM tbl_ProductCatalogue WHERE WarehouseSKU = '" + product.WarehouseSKU + "' AND WarehouseSKU!='" + sku + "'");
                    int Count = Convert.ToInt32(obj_dal.Get_SingleValue(sb.ToString()));
                    // If Row count value is grater then 0 so Email id must be duplicate
                    if (Count > 0)
                    {
                        // Error message in red color
                        ViewBag.ErrorMessage = "Warehouse Already exist";
                    }
                    else
                    {
                        sb.Clear();
                        // Applied Select query for get value of ProductImage
                        sb.Append("SELECT ProductImage FROM tbl_ProductCatalogue where WarehouseSKU = '" + sku + "'");
                        string Image = obj_dal.Get_SingleValue(sb.ToString());
                        //string UploadImage = "/UploadedImage / " + Image;

Product_CatalogAndWarehouse_Inventory/Views/ProductCatalogue/ProductList.cshtml
@model Product_CatalogAndWarehouse_Inventory.Models.ProductCatalogueModel

@{
    ViewBag.Title = "Product List";
}

<div class="alert alert-success alert-dismissable" style="display:none" id="successMsg">
    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
    <a class="alert-link" href="#"></a>

</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <form method="post" id="myForm" class="form-horizontal">
        <div class="row">
            <div class="form-group">
                <label class="col-sm-1 control-label">Show</label>
                <div class="col-sm-1">
                    @Html.DropDownList("PageSize", new SelectList(Model.PageSizeList, "Value", "Text", Model.PageSize),
                        new { onchange = "PageSizeChangefunc(this.value)", id = "pagesize", @class = "form-control" })
                </div>
                <label class="col-sm-1 control-label">Search</label>
                <div class="col-sm-2">
                    @Html.TextBox("search", "", Model.search, new { onkeyup = "Search(this.value)", @class = "form-control" })
                </div>
                <div class="col-sm-2">
                    <button type="button" class="btn btn-w-m btn-primary"
                            onclick="ADDProduct(this.value)" style="margin-left:60px">Add Product</button>
                </div>
            </div>
            @if (ViewBag.infoMessage != null)
            {
                @ViewBag.infoMessage
            }
            @foreach (var item in Model.ProductList)
            {
                <div class="col-md-3">
                    <div class="ibox">
                        <div class="ibox-content product-box" style="height:280px">
                            <div class="product-imitation" id="dropzone">
                                @if (!string.IsNullOrEmpty(item.FileImage))
                                {
                                    <img src="/UploadedImage/@item.FileImage" id="dropzoneimg" alt="">
                                }
                                else
                                {
                                    <img src="/DefaultImage/thumbnail-default.jpg" alt="" id="dropzoneimg" />
                                }
                            </div>
                            <div class="product-desc" style="height:50px">
                                <span class="product-price">
                                    £@item.TotalCost
                                </span>
                                <div class="small m-t-xs" style="text-align:center">
                                    @item.ProductName
                                </div>
                            </div>
                            <div class="product-button">
                                <div class="m-t text-righ">
                                    <button value="@item.WarehouseSKU" type="button" class="btn btn-xs btn-primary"
                                            onclick="ViewProduct(this.value)" style="margin-left:60px">View</button>
                                    <button value="@item.WarehouseSKU" type="button" class="btn btn-success btn-xs"
                                            onclick="EditProduct(this.value)" style="margin-left:20px">Edit</button>
                                    <button value="@item.WarehouseSKU" type="button" class="btn btn-danger btn-xs"
                                            onclick="DeleteProduct(this.value)" style="margin-left:20px">Delete</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>

        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_0_paginate">
            <ul class="pagination">
                @if (Model.Page_Number != 1)
                {
                    <li>
                        @Html.ActionLink("Prev", "ProductList", new { Page = Model.Page_Number - 1, pageSize = Model.PageSize, search = Model.search })
                        @Html.ActionLink("First", "ProductList", new { Page = 1, pageSize = Model.PageSize, search = Model.search })
                    </li>
                }
                @for (int i = Model.StartPage; i <= Model.EndPage; i++)
                {
                    if (i == Model.Page_Number)
                    {
                        <li class="active">
                            @Html.ActionLink(i.ToString(), "ProductList", new { Page = Model.Page_Number, pageSize = Model.PageSize, search = Model.search })
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink(i.ToString(), "ProductList", new { Page = i, pageSize = Model.PageSize, search = Model.search })
                        </li>
                    }
                }
                @if (Model.Page_Number != Model.Page_Count)
                {
                    <li>
                        @Html.ActionLink("Next", "ProductList", new { Page = Model.Page_Number + 1, pageSize = Model.PageSize, search = Model.search })
                        @Html.ActionLink("Last", "ProductList", new { Page = Model.Page_Count, pageSize = Model.PageSize, search = Model.search })
                    </li>
                }
            </ul>
        </div>
    </form>
</div>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="container">
            <div class="modal-header" style="padding:2px">
                <a href="#" data-dismiss="modal"> </a>
                <div class="ibox-tools">
                    <span id="myModalLabel" style="margin-right:900px;"><font size="+2"><b></b></font></span>
                    <a class="close-link" data-dismiss="modal">
                        <i class="fa fa-times" style="margin-right:15px"></i>
                    </a>
                </div>
            </div>
            <div class="modal-body">
                <fieldset id="modal_form">
                </fieldset>
                <div class="modal-footer" style="padding:8px">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    #dropzone {
        text-align: center;
        padding: 0px 0;
        background-color: #f8f8f9;
        color: #bebec3;
        font-weight: 600;
    }

    #dropzoneimg {
        object-fit: contain;
        width: 100%;
        height: 180px;
        padding: 4px;
        display: block;
    }

    #container {
        width: 1100px;
        height: 700px;
        position: fixed;
        left: calc(50% - 500px);
    }
</style>

@section scripts{
    <script>
        pageSize = document.getElementById("pagesize").value;
        function PageSizeChangefunc(pageSize)
        {
            window.location.href = "/ProductCatalogue/ProductList?pageSize=" + pageSize;
        }

        var delayTimer;
        function Search(search) {
            clearTimeout(delayTimer);
            delayTimer = setTimeout(() => {
                window.location.href = "/ProductCatalogue/ProductList?pageSize=" + pageSize + "&search=" + search;
            }, 1000);
        }

        function ADDProduct() {
            window.location.href = "/ProductCatalogue/AddCatalogueProduct";
        }
        
        function EditProduct(WarehouseSKU) {
            window.location.href = "/ProductCatalogue/AddCatalogueProduct?sku=" + WarehouseSKU;
        }

        function ViewProduct(warehouseSKU) {
            $.ajax({
                    url : '@Url.Action("ViewProduct", "ProductCatalogue")',
                    method: 'GET',
                    data: { warehouseSKU: warehouseSKU },
                    success: function (response) {
                        $("#modal_form").html(response);                       
                        $("#editModal").modal('show');
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
        }

        function DeleteProduct(sku) {
            swal({
                title: "Are you sure you want to delete this Product?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false

            }, function () {
                $.ajax({
                    url: "DeleteProduct",
                    method: 'GET',
                    data: { sku: sku },
                    success: function (response) {
                        if (response.iserror == false) {
                            swal("Deleted!", response.message);
                            document.getElementById('successMsg').innerText = response.message  
                            clearTimeout(delayTimer);
                            delayTimer = setTimeout(() => {
                                window.location.href = "/ProductCatalogue/ProductList?pageSize=" + pageSize;
                            }, 2000);
                        }
                                              
                    },
                    failure: function (response) {
                        alert(response.responseText);
                    },
                    error: function (response) {
                        alert(response.responseText);
                    }
                });
            });
        }        
    </script>
}

Product_CatalogAndWarehouse_Inventory/Views/ProductCatalogue/ViewProduct.cshtml
@model Product_CatalogAndWarehouse_Inventory.Models.ProductCatalogueModel

<div class="row">
    <div class="col-sm-12">
        @Html.TextBox("SkuName", (String)ViewBag.Warehouse, new { @class = "form-control", @style = "font-weight:bold" })
    </div>
    @if (Model != null)
    {
        <div class="col-lg-6 b-r">
            <div id="dropzone">
                @if (!string.IsNullOrEmpty(Model.FileImage))
                {
                    <img src="/UploadedImage/@Model.FileImage" id="dropzoneimg" alt="">
                }
                else
                {
                    <img src="/DefaultImage/thumbnail-default.jpg" alt="" id="dropzoneimg" />
                }
            </div>
            <br />
            <div class="form-group">
                <label class="col-sm-6 control-label">Product Name</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ProductName, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">WarehouseSKU</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.WarehouseSKU, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Description</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Description, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">HSCode</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.HSCode, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group" style="text-align:center">
                <label>Product Dimensions:</label>
            </div>

            <div class="form-group">
                <label class="col-sm-6 control-label">Width</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Width, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Length</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Length, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Material Composition</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.MaterialComposition, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Varsany Bag</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.VarsanyBag, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Colour</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Colour, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="form-group">
                <label class="col-sm-6 control-label">Product Weight</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ProductWeight, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Box Size</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.BoxSize, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Box Quantity</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.BoxQuantity, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Manufacture</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Manufaturer, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Mailing Bag</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.MailingBag, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Size</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Size, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group" style="text-align:center">
                <label>Cost</label>
            </div>

            <div class="form-group">
                <label class="col-sm-6 control-label">Product Cost</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ProductCost, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Commision</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Commision, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Shipping Cost</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ShippingCost, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Duty</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Duty, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group" style="text-align:center">
                <label>Total Cost</label>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Chinese Yuan</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.ChineseYuan, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">US Dollar</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.UsDollar, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Euros</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.Euros, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-6 control-label">Total Cost</label>
                <div class="col-sm-6">
                    @Html.TextBoxFor(m => m.TotalCost, new { @class = "form-control", @style = "border:none" })
                </div>
            </div>
        </div>
    }
</div>